# Generated by Django 2.0.1 on 2020-05-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
